version: '3.0'
services:
  main:
    container_name: main
    build: 
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      -5000:5000
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: postgres
    image: postgres:12
    .env_file:
      - .env
    environment:
      - PG_DATA: /var/lib/postgressql/data
    ports:
      -5432:5432
    volumes:
      -pgdata: /var/lib/postgressql/data
    restart: always

volumes:
  pgdata:
